app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
   
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

app_accueil:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    requirements:
        _method:  GET

lost_password:
    path:     /lost_password/
    defaults: { _controller: AppBundle:Default:lostPassword}