AppBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ImageRepository
    table: images
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    filename:
        type:         string
        length:       100

    # changed when files are uploaded, to force preUpdate and postUpdate to fire
    updated:
        type:         datetime
        nullable:     true

    # ... other fields ...
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]